# NumPy Practice Notebook

This notebook contains a series of practice problems to help you understand and apply core concepts in NumPy.

---

## 🧩 1. Array Creation
**Question:** Create the following arrays using NumPy:
1. A 1D array with numbers from 0 to 9
2. A 2D array of shape (3, 3) filled with zeros
3. A 2D array of shape (2, 4) filled with ones
4. A 3x3 identity matrix


---


In [96]:
#1
import numpy as np # import numpy to use it over the whole file

arr1 = np.arange(10) # create an array of numbers from 0 to 9
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
arr2 = np.zeros((3,3)) # 3x3 matrix full of zeros
arr2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [98]:
arr3 = np.ones((2,4)) # creates 2x4 matrix full of one
arr3

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [99]:
arr4 = np.eye(3,3) #creates 3x3 identity matrix
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])


## 🧪 2. Array Inspection
**Question:** Given a NumPy array `arr`, print:
1. Its shape
2. Its data type
3. The number of dimensions
4. The total number of elements

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```

---


In [100]:
arr5 = np.array([[1, 2, 3], [4, 5, 6]]) # creating the array i’m gonna work on
arr5

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
arr5.shape # returns the shape of the array as a tuple

(2, 3)

In [102]:
arr5.dtype # returns the data type of the data into the array

dtype('int32')

In [103]:
arr5.ndim # returns the number of dimensions of the array

2

In [104]:
arr5.shape[0] * arr5.shape[1] # using shape proprety to get the number of elements in the array

6


## 🔍 3. Indexing and Slicing
**Question:** Using the array below, do the following:
1. Slice the first two rows
2. Get the last column
3. Extract the element in the second row and third column
4. Reverse the rows

```python
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

```


In [105]:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]]) # creating the array we’re gonna use
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [106]:
arr[:2 , :] # getting the first two rows

array([[10, 20, 30],
       [40, 50, 60]])

In [107]:
arr[: , -1] # getting the last column

array([30, 60, 90])

In [108]:
arr[1,2] # getting the element in the second row and third column

60

In [109]:
arr[::-1] # reverse the rows

array([[70, 80, 90],
       [40, 50, 60],
       [10, 20, 30]])


---

## 🔁 4. More Slicing Practice
**Question:**
Given the array below, extract:
1. All even numbers
2. The second and third rows
3. The last two columns
4. A subarray containing the middle 2x2 block

```python
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]])

```


In [110]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]]) # creating the matrix we’re gonna use
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [111]:
arr[arr%2==0] # getting only the even numbers

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [112]:
arr[1:3,:] # getting the second and third rows

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [113]:
arr[: , 2:] # getting 2nd column onwards

array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16]])

In [114]:
arr[1:3,1:3] # getting the middle 2x2 sub array

array([[ 6,  7],
       [10, 11]])


---

## ➕ 5. Arithmetic Operations
**Question:** Perform the following using NumPy arrays:
1. Add two arrays element-wise
2. Multiply two arrays element-wise
3. Raise all elements of an array to the power of 2

```python
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

```

---


In [115]:
arr1 = np.array([1, 2, 3]) # getting our matrices ready for work
arr2 = np.array([4, 5, 6])

In [116]:
arr1 + arr2 # element wise addition

array([5, 7, 9])

In [117]:
arr1 *arr2 # element wise multiplication

array([ 4, 10, 18])

In [118]:
arr1 **2 # element wise square of arr1

array([1, 4, 9])


## 📏 6. Broadcasting
**Question:** Use broadcasting to:
1. Add a 1D array to each row of a 2D array
2. Multiply each row of a 2D array by a 1D array
3. Subtract a scalar from each element in an array
4. Add a column vector to each column of a matrix

```python
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([10, 20, 30])
C = np.array([[1], [2]])

```


In [124]:
import numpy as np
# getting our matrices ready and print them for better visualization
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([10, 20, 30])
C = np.array([[1], [2]])

print(A , end='\n\n')
print(B ,end ='\n\n')
print(C)

[[1 2 3]
 [4 5 6]]

[10 20 30]

[[1]
 [2]]


In [125]:
A + B  #Add a 1D array to each row of a 2D array

array([[11, 22, 33],
       [14, 25, 36]])

In [126]:
A * B #Multiply each row of a 2D array by a 1D array

array([[ 10,  40,  90],
       [ 40, 100, 180]])

In [127]:
A - 1 #Subtract a scalar from each element in an array

array([[0, 1, 2],
       [3, 4, 5]])

In [128]:
A + C # Add a column vector to each column of a matrix

array([[2, 3, 4],
       [6, 7, 8]])


---

## 🔁 7. More Broadcasting Practice
**Question:** Try these:
1. Add a 1D array of shape (4,) to a 2D array of shape (3,4)
2. Multiply a (3,1) column array to a (1,4) row array and observe the shape
3. Add a scalar to the entire array

```python
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400])
C = np.array([[2], [3], [4]])

```


In [130]:
A = np.arange(12).reshape(3, 4)
B = np.array([100, 200, 300, 400]) # getting our arrays ready
C = np.array([[2], [3], [4]])

In [131]:
B + A # Add a 1D array of shape (4,) to a 2D array of shape (3,4)

array([[100, 201, 302, 403],
       [104, 205, 306, 407],
       [108, 209, 310, 411]])

In [132]:
# Multiply a (3,1) column array to a (1,4) row array and observe the shape
print(C * B)

(C * B).shape

[[ 200  400  600  800]
 [ 300  600  900 1200]
 [ 400  800 1200 1600]]


(3, 4)

In [133]:
# Add a scalar to the entire array
print(A)

A + 5

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])


---

## 🔃 8. Reshaping and Flattening
**Question:**
1. Reshape a 1D array of 12 elements into a 3x4 matrix
2. Flatten a 2D array into a 1D array

```python
arr = np.arange(12)

```


In [134]:
arr = np.arange(12) # creating an array of 12 elements
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [135]:
arr = arr.reshape((3,4)) # reshape the array to 3x4
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
arr.flatten() # flatten the 2D array into 1D array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


---

## 🔗 9. Stacking and Splitting
**Question:** Stack and split arrays:
1. Stack two (2, 2) arrays vertically and horizontally
2. reshape a (4, 4) array into array of shape (2, 8)


---


In [137]:
# getting our arrays ready for work
arr1 = [
    [1,2],
    [3,4]
]

arr2 = [
    [5,6],
    [7,8]
]

In [ ]:
np.vstack((arr1,arr2)) # stack the arrays vertically

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [138]:
np.hstack((arr1 , arr2)) # stack the arrays horizontally

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [140]:
# creating a 4x4 2D array for reshape and applying the new shape 2x8 on it
arr =np.array( [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])

arr.reshape((2,8))

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16]])


## 🧠 10. Boolean Masking
**Question:**
Given an array:
1. Select all elements > 10
2. Replace all even numbers with -1

```python
arr = np.array([[5, 10, 15], [20, 25, 30]])

```


In [141]:
# getting our array ready
arr = np.array([[5, 10, 15], [20, 25, 30]])
arr

array([[ 5, 10, 15],
       [20, 25, 30]])

In [ ]:
arr[arr>10] # getting only the elements larger than 10

array([15, 20, 25, 30])

In [142]:
np.where(arr%2==0 ,-1, arr ) # replace every even number with -1 and leave odd numbers as it is

array([[ 5, -1, 15],
       [-1, 25, -1]])


---

## 🧮 11. Aggregation
**Question:** Calculate:
1. Sum of all elements
2. Mean of each column
3. Max value in each row
4. Standard deviation of the array

```python
arr = np.array([[1, 2, 3], [4, 5, 6]])

```


In [143]:
# getting our array ready
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [144]:
np.sum(arr) # getting the sum of all the elements in the array

21

In [145]:
np.mean(arr) # getting the mean of the elements in the array

3.5

In [146]:
np.max(arr) # getting the max number from the array

6

In [147]:
np.std(arr) # getting standard deviation of the array

1.707825127659933


---

## 🧲 12. Dot Product and Matrix Multiplication
**Question:**
1. Multiply two matrices using `np.dot`

```python
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

```


In [148]:
# getting our arrays ready to work on them
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

In [149]:
# applying dot product on them
A.dot(B)

array([[19, 22],
       [43, 50]])


---

## 🔢 13. Random Numbers
**Question:**
1. Generate a 2x3 array of random numbers between 0 and 1
2. Generate 10 random integers between 50 and 100



In [150]:
# creating an array of the shape 2x3 in the range from 0 to 1
np.random.rand(2,3)

array([[0.99920709, 0.80164655, 0.15014531],
       [0.14072872, 0.58825579, 0.06393534]])

In [152]:
# creating an array of the shape 10, with random integers from range 50 to 100
np.random.randint(50,100 , (10,))

array([83, 75, 51, 68, 61, 67, 97, 90, 57, 66])


---

## 📐 14. Linear Algebra
**Question:**
1. Find the rank of a matrix
2. Compute the inverse of a matrix
3. Compute the determinant of a matrix



---


In [153]:
# create a matrix with low rank
arr = [
    [2,4],
    [4,8]
]
arr

[[2, 4], [4, 8]]

In [154]:
# returning the rank of the matrix
np.linalg.matrix_rank(arr)

1

In [156]:
# creating a matrix that has inverse and getting the inverse of it
arr_inv = [
    [1,4],
    [5,8]
]
np.linalg.inv(arr_inv)

array([[-0.66666667,  0.33333333],
       [ 0.41666667, -0.08333333]])

In [157]:
# getting the determinant of the above array
np.linalg.det(arr_inv)

-11.999999999999995


## ⭐ Bonus Challenge
**Question:**
Given a 2D array of shape (6, 6), extract all 3x3 submatrices (using slicing) and store them in a list.



In [162]:
# creating the matrix we are gonna work on it
arr = np.random.randint(0,50 , (6,6))
arr

array([[17, 35,  8, 36, 13, 44],
       [41, 42, 12, 12, 42, 48],
       [25, 47,  6, 20, 11, 24],
       [41, 35,  2, 34, 31,  2],
       [41, 35, 44, 21, 27, 28],
       [11,  1, 31, 16,  7, 25]])

In [160]:
arr.shape # print the shape of the array for better understanding of it

(6, 6)

In [166]:
mats = [] # list to store all the possible matrices

for row in range(arr.shape[0]-2): # loop over the rows of the matrix
    for col in range(arr.shape[1]-2): # loop over the cloumns of the matrix
        matrix = arr[row:row+3 ,col : col+3 ] # getting the sub matrix from the large one
        mats.append( matrix) # store it in the list
mats # printing the list

[array([[17, 35,  8],
        [41, 42, 12],
        [25, 47,  6]]),
 array([[35,  8, 36],
        [42, 12, 12],
        [47,  6, 20]]),
 array([[ 8, 36, 13],
        [12, 12, 42],
        [ 6, 20, 11]]),
 array([[36, 13, 44],
        [12, 42, 48],
        [20, 11, 24]]),
 array([[41, 42, 12],
        [25, 47,  6],
        [41, 35,  2]]),
 array([[42, 12, 12],
        [47,  6, 20],
        [35,  2, 34]]),
 array([[12, 12, 42],
        [ 6, 20, 11],
        [ 2, 34, 31]]),
 array([[12, 42, 48],
        [20, 11, 24],
        [34, 31,  2]]),
 array([[25, 47,  6],
        [41, 35,  2],
        [41, 35, 44]]),
 array([[47,  6, 20],
        [35,  2, 34],
        [35, 44, 21]]),
 array([[ 6, 20, 11],
        [ 2, 34, 31],
        [44, 21, 27]]),
 array([[20, 11, 24],
        [34, 31,  2],
        [21, 27, 28]]),
 array([[41, 35,  2],
        [41, 35, 44],
        [11,  1, 31]]),
 array([[35,  2, 34],
        [35, 44, 21],
        [ 1, 31, 16]]),
 array([[ 2, 34, 31],
        [44, 21, 27],
    

In [169]:
# for more dynammic control over the code to fit more matrices 
def get_sub_matrices(arr : np.ndarray, sub_arr_shape : tuple =(3,3)) -> list[np.ndarray] :
    '''
    a function that takes an array as input and extract all possible sub arrays from it using indexing (moving on the array like window and take sub arrays from it)
    input -> arr : array of any shape , sub_arr_shape : the shape of the desired sub arrays
    output -> returns mats : a list containing all the possible sub arrays from the passed array
    '''
    mats = [] # list to store all the possible matrices

    for row in range(( arr.shape[0] ) - ( sub_arr_shape[0] - 1 )): # loop over the rows of the matrix and exclude some of the last rows (depending on the shape of the sub matrix)
        for col in range(( arr.shape[1] ) - ( sub_arr_shape[1] - 1 )): # loop over the cloumns of the matrix and exclude some of the last columns (depending on the shape of the sub matrix)
            matrix = arr[row: (row + sub_arr_shape[0]) ,col : (col + sub_arr_shape[1]) ] # getting the sub matrix from the large one
            mats.append( matrix) # store it in the list
    return mats # printing the list
get_sub_matrices(arr )

[array([[17, 35,  8],
        [41, 42, 12],
        [25, 47,  6]]),
 array([[35,  8, 36],
        [42, 12, 12],
        [47,  6, 20]]),
 array([[ 8, 36, 13],
        [12, 12, 42],
        [ 6, 20, 11]]),
 array([[36, 13, 44],
        [12, 42, 48],
        [20, 11, 24]]),
 array([[41, 42, 12],
        [25, 47,  6],
        [41, 35,  2]]),
 array([[42, 12, 12],
        [47,  6, 20],
        [35,  2, 34]]),
 array([[12, 12, 42],
        [ 6, 20, 11],
        [ 2, 34, 31]]),
 array([[12, 42, 48],
        [20, 11, 24],
        [34, 31,  2]]),
 array([[25, 47,  6],
        [41, 35,  2],
        [41, 35, 44]]),
 array([[47,  6, 20],
        [35,  2, 34],
        [35, 44, 21]]),
 array([[ 6, 20, 11],
        [ 2, 34, 31],
        [44, 21, 27]]),
 array([[20, 11, 24],
        [34, 31,  2],
        [21, 27, 28]]),
 array([[41, 35,  2],
        [41, 35, 44],
        [11,  1, 31]]),
 array([[35,  2, 34],
        [35, 44, 21],
        [ 1, 31, 16]]),
 array([[ 2, 34, 31],
        [44, 21, 27],
    


---

Happy coding! 🎯


# *always*